#!/usr/bin/env bash
allThreads=("test_utils.py" "test_client.py" "utils.py" "client.py" "fixtures.py")

mkdir -p "0x03-Unittests_and_integration_tests"

for t in ${allThreads[@]}; do

    if [[ $t == *".py"* ]]; then
        echo -e "#!/usr/bin/env python3\n" > "./0x03-Unittests_and_integration_tests/$t" && chmod +x "./0x03-Unittests_and_integration_tests/$t"
    else
        # echo -e "#include \"0x03-Unittests_and_integration_tests.h\"" "" "" "" "" ""> "./0x03-Unittests_and_integration_tests/$t"
        touch "./0x03-Unittests_and_integration_tests/$t"
    fi

done

echo -e "# ALX Software Engineering Programme Project: 0x03. Unittests and Integration Tests" > "./0x03-Unittests_and_integration_tests/README.md"

echo -e "#!/bin/bash\ngit add . && git commit -m '0x03. Unittests and Integration Tests' && git push"  > "./0x03-Unittests_and_integration_tests/correction" && chmod +x "./0x03-Unittests_and_integration_tests/correction"

cp "../alx-higher_level_programming/0x05-python-exceptions/clean_up_corrections" "./0x03-Unittests_and_integration_tests/"

cd ./0x03-Unittests_and_integration_tests

# mkdir -p "0x1C-makefiles"

# for t in ${allThreads[@]}; do

#     if [[ $t == *".py"* ]]; then
#         echo -e "#!/usr/bin/python3\n" > "./0x1C-makefiles/$t" && chmod +x "./0x1C-makefiles/$t"
#     else
#         # echo -e "#include \"sort.h\"\n" > "./0x1C-makefiles/$t"
#         touch "./0x1C-makefiles/$t"
#     fi

# done

# echo -e "# ALX Software Engineering Programme Project: 0x1C. C - Makefiles" > "./0x1C-makefiles/README.md"

# cp "0x15-file_io/correction" "./0x1C-makefiles/"

# cd /root/alx-low_level_programming/0x1C-makefiles