#!/usr/bin/env bash
allThreads=("0-add.py" "1-concat.py" "2-floor.py" "3-to_str.py" "4-define_variables.py" "5-sum_list.py" "6-sum_mixed_list.py" "7-to_kv.py" "8-make_multiplier.py" "9-element_length.py" "100-safe_first_element.py" "101-safely_get_value.py" "102-type_checking.py")

mkdir -p "0x00-python_variable_annotations"

for t in ${allThreads[@]}; do

    if [[ $t == *".py"* ]]; then
        echo -e "#!/usr/bin/python3\n" > "./0x00-python_variable_annotations/$t" && chmod +x "./0x00-python_variable_annotations$t"
    else
        # echo -e "#include \"0x00-python_variable_annotations.h\"" "" "" "" "" ""> "./0x00-python_variable_annotations/$t"
        touch "./0x00-python_variable_annotations/$t"
    fi

done

echo -e "# ALX Software Engineering Programme Project: 0x00. Python - Variable Annotations" > "./0x00-python_variable_annotations/README.md"

echo -e "#!/bin/bash\ngit add . && git commit -m '0x00. Python - Variable Annotations' && git push"  > "./0x00-python_variable_annotations/correction" && chmod +x "./0x00-python_variable_annotations/correction"

cp "../alx-higher_level_programming/0x05-python-exceptions/clean_up_corrections" "./0x00-python_variable_annotations/"

cd ./0x00-python_variable_annotations

# mkdir -p "0x1C-makefiles"

# for t in ${allThreads[@]}; do

#     if [[ $t == *".py"* ]]; then
#         echo -e "#!/usr/bin/python3\n" > "./0x1C-makefiles/$t" && chmod +x "./0x1C-makefiles/$t"
#     else
#         # echo -e "#include \"sort.h\"\n" > "./0x1C-makefiles/$t"
#         touch "./0x1C-makefiles/$t"
#     fi

# done

# echo -e "# ALX Software Engineering Programme Project: 0x1C. C - Makefiles" > "./0x1C-makefiles/README.md"

# cp "0x15-file_io/correction" "./0x1C-makefiles/"

# cd /root/alx-low_level_programming/0x1C-makefiles